sudo: false
language: python
matrix:
  include:
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.5
      env: TOXENV=coverage
install:
  - pip install tox
  - if [ "$TOXENV" = "coverage" ]; then pip install coveralls; fi
script:
  - export PYTHONPATH=$PYTHONPATH:`pwd`
  - tox
after_success:
  - if [ "$TOXENV" = "coverage" ]; then coveralls; fi
