language: python
env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=coverage
install:
  - pip install tox
  - if [ "$TOXENV" = "coverage" ]; then pip install coveralls; fi
script:
  - export PYTHONPATH=$PYTHONPATH:`pwd`
  - tox
after_success:
  - if [ "$TOXENV" = "coverage" ]; then coveralls; fi
